<?php

/**
 * @file
 * Empty paragraph killer: because users are sometimes overzealous
 * with the return key.
 */

/**
 * Implements hook_filter_info().
 */
function emptyparagraphkiller_filter_info() {
  $filters['emptyparagraphkiller'] = array(
    'title' => t('Empty paragraph filter'),
    'description' => t('When entering more than one carriage return, only the first will be honored.'),
    'process callback' => 'emptyparagraphkiller__emptyparagraphkiller_process',
    'cache' => FALSE,
    'tips callback' => 'emptyparagraphkiller_emptyparagraphkiller_tips',
    'weight' => 10,
  );
  //$filters[] = array(); The info for the preceding space destroyer filter
  return $filters;
}

/**
 * Process callback for the emptyparagraphkillter filter.
 */
function emptyparagraphkiller__emptyparagraphkiller_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  $text = preg_replace('#<p[^>]*>(\s|&nbsp;?)*</p>#', '', $text);
  return $text;
}

/**
 * Tips callback for emptyparagraphkiller
 */
function emptyparagraphkiller_emptyparagraphkiller_tips($filter, $format, $long) {
  if ($long) {
    return '<p>' . t('Your typing habits may include hitting the return key twice when completing a paragraph. This site will accomodate your habit, and ensure the content is in keeping with the the stylistic formatting of the site\'s theme.') . '</p>';
  }
  else {
    return t('Empty paragraph killer - multiple returns will not break the site\'s style.');
  }
}
